CREATE DATABASE IF NOT EXISTS smartcampus;
USE smartcampus;

CREATE TABLE sala (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(191) NOT NULL UNIQUE,
  criadoEm DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE sensor (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipo VARCHAR(191) NOT NULL,
  deviceId VARCHAR(191) NOT NULL,
  salaId INT NOT NULL,
  criadoEm DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  FOREIGN KEY (salaId) REFERENCES sala(id)
);

CREATE TABLE leitura (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipo VARCHAR(191) NOT NULL,
  valor DOUBLE NOT NULL,
  timestamp DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  sensorId INT NOT NULL,
  FOREIGN KEY (sensorId) REFERENCES sensor(id)
);

CREATE TABLE consumodiario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sensorId INT NOT NULL,
  data DATE NOT NULL,
  consumo_kwh DOUBLE NOT NULL DEFAULT 0,
  atualizadoEm DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE(sensorId, data),
  FOREIGN KEY (sensorId) REFERENCES sensor(id)
);
